config/routes.rb
Rails.application.routes.draw do
  get 'creators/index'
  get 'creators/show'
  devise_for :companies
  resources :companies, only: [:index, :show, :edit, :update]
  resources :products

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :products
end

app/models/company_products_tagging.rb
class CompanyProductsTagging < ApplicationRecord
  belongs_to :products
  belongs_to :tags
end

app/models/creator.rb
class Creator < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  belongs_to :category
  has_many :tags, through: :company_products_tagging
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :products, through: :company_products_tagging
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(current_company.id)
  end

  def edit
    @company = Company.find(current_company.id)
  end

  def update
    @company = Company.find(current_company.id)
    @company.update!(company_params)
    redirect_to companies_url
  end

  private

  def company_params
    params.require(:company).
      permit(:name, :introduction, :address, :email, :number_of_employees, :capital,
         :date_of_establishment, :corporate_site, :image)
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.save!
    redirect_to products_url
  end

  def edit
  end

  private

  def product_params
    params.require(:product).
      permit(:name, :introduction, :available_from, :available_to, :can_be_provided, :company_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/companies/edit.html.erb
<%= form_with model: @company, local: true do |f|%>
  <div>
    <%= f.label :image %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :name %>
  </div>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :introduction %>
  </div>
  <div>
    <%= f.text_area :introduction %>
  </div>
  <div>
    <%= f.label :address %>
  </div>
  <div>
    <%= f.text_area :address %>
  </div>
  <div>
    <%= f.label :email %>
  </div>
  <div>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :number_of_employees %>
  </div>
  <div>
    <%= f.number_field :number_of_employees %>
  </div>
  <div>
    <%= f.label :capital %>
  </div>
  <div>
    <%= f.number_field :capital %>
  </div>
  <div>
    <%= f.label :Date_of_establishment %>
  </div>
  <div>
    <%= f.date_select :Date_of_establishment %>
  </div>
  <div>
    <%= f.label :corporate_site %>
  </div>
  <div>
    <%= f.text_area :corporate_site %>
  </div>
    <%= f.submit %>
<% end %>

app/views/companies/index.html.erb
<% @companies.each do |company| %>
  <li><%= link_to company.name, "/companies/#{company.id}" %></li>
<% end %>
<%= link_to '新規登録', new_company_registration_path %>

app/views/companies/new.html.erb
<h1>Companies#new</h1>
<p>Find me in app/views/companies/new.html.erb</p>

<%= form_with model: @campany, local: true do |f|%>
  <div>
    <%= f.label :name %>
  </div>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :introduction %>
  </div>
  <div>
    <%= f.text_area :introduction %>
  </div>
  <div>
    <%= f.label :address %>
  </div>
  <div>
    <%= f.text_area :address %>
  </div>
  <div>
    <%= f.label :mail %>
  </div>
  <div>
    <%= f.email_field :mail %>
  </div>
  <div>
    <%= f.label :number_of_employees %>
  </div>
  <div>
    <%= f.number_field :number_of_employees %>
  </div>
  <div>
    <%= f.label :capital %>
  </div>
  <div>
    <%= f.number_field :capital %>
  </div>
  <div>
    <%= f.label :Date_of_establishment %>
  </div>
  <div>
    <%= f.date_select :Date_of_establishment %>
  </div>
  <div>
    <%= f.label :corporate_site %>
  </div>
  <div>
    <%= f.text_area :corporate_site %>
  </div>
    <%= f.submit %>
<% end %>

app/views/companies/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/companies/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/companies/show.html.erb
<div>
  image
</div>
<div>
  <%= image_tag @company.image, size: '320x240' if @company.image.attached? %>
</div>
<div>
  name
</div>
<div>
  <%= @company.name %>
</div>
<div>
  introduction
</div>
<div>
  <%= @company.introduction %>
</div>
<div>
  address
</div>
<div>
  <%= @company.address %>
</div>
<div>
  email
</div>
<div>
  <%= @company.email %>
</div>
<div>
  number_of_employees
</div>
<div>
  <%=  @company.number_of_employees %>
</div>
<div>
  capital
</div>
<div>
  <%= @company.capital %>
</div>
<div>
  Date_of_establishment
</div>
<div>
  <%= @company.date_of_establishment %>
</div>
<div>
  corporate_site
</div>
<div>
  <%= @company.corporate_site %>
</div>
  <%= link_to '編集', edit_company_path %>

app/views/creators/index.html.erb
<h1>Creators#index</h1>
<p>Find me in app/views/creators/index.html.erb</p>

app/views/creators/show.html.erb
<h1>Creators#show</h1>
<p>Find me in app/views/creators/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
<% end %>
<%= link_to '新規登録', new_product_path %>

app/views/products/new.html.erb
<%= form_with model: @product, local: true do |f|%>
  <div>
    <%= f.label :name %>
  </div>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :category %>
  </div>
  <div>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div>
    <%= f.label :introduction %>
  </div>
  <div>
    <%= f.text_area :introduction %>
  </div>
  <div>
    <%= f.label :available_from %>
  </div>
  <div>
    <%= f.date_select :available_from %>
  </div>
  <div>
    <%= f.label :available_to %>
  </div>
  <div>
    <%= f.date_select :available_to %>
  </div>
  <%= f.hidden_field :company_id, value: current_company.id %>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<div>
  name
</div>
<div>
  <%= @product.name %>
</div>
<div>
  introduction
</div>
<div>
  <%= @product.introduction %>
</div>
<div>
  category
</div>
<div>
  <%= @product.category.name %>
</div>
<div>
  available_from
</div>
<div>
  <%= @product.available_from %>
</div>
<div>
  available_to
</div>
<div>
  <%= @product.available_to %>
</div>
<div>
  company
</div>
<div>
  <%= @product.company.name %>
</div>
  <%= link_to '編集', edit_company_path %>